First version of tests & TSLint/typo fixes
ESD6-blockr/blockr-p2p-lib pull request #10
Opened 2019-05-28 13:57 UTC by Juuldamen

2019-05-28 14:02 UTC, quintaartsen approved these changes

2019-06-04 07:28 UTC, RikvanSpreuwel commented on src/__tests__/connectionService.test.ts
> +    testPort = "65535";
Define a constant for this variable.

2019-06-04 07:32 UTC, RikvanSpreuwel commented on src/__tests__/message.model.test.ts
> +    type = "ping";
If this variable doesn't change, please consider making it a constant.

2019-06-04 07:35 UTC, RikvanSpreuwel commented on src/__tests__/message.model.test.ts
> +    body = "body";
If this variable doesn't change, please consider making it a constant.

Example (outside of the beforeAll() method):
const body = "ping";

2019-06-04 07:45 UTC, RikvanSpreuwel commented on src/__tests__/routingTable.model.test.ts
> +        expect(peerNode).not.toBeUndefined();
Please change "expect(peerNode).not.toBeUndefined();" to:

expect(peerNode).toBeDefined();

2019-06-04 07:46 UTC, RikvanSpreuwel commented on src/__tests__/routingTable.model.test.ts
> +        expect(peerNode).not.toBeUndefined();
Please change not.toBeUndefined() to .toBeDefined();

2019-06-04 07:47 UTC, RikvanSpreuwel commented on src/__tests__/routingTable.model.test.ts
> +        expect(peerNode2).not.toBeUndefined();
Please change not.toBeUndefined() to .toBeDefined();

2019-06-04 07:49 UTC, RikvanSpreuwel commented on src/__tests__/routingTable.model.test.ts
> +        expect(valPeerNode).not.toBeUndefined();
Please change not.toBeUndefined() to .toBeDefined();

2019-06-04 07:57 UTC, RikvanSpreuwel requested changes
Overall, change all .not.toBeUndefined() calls to .toBeDefined(), this does exactly the same, but removes the useless .not call.

2019-06-04 09:23 UTC, RikvanSpreuwel approved these changes

2019-06-04 09:25 UTC, merged