Improved code coverage & fixed sendMessage tests
ESD6-blockr/blockr-p2p-lib pull request #14
Opened 2019-06-06 10:19 UTC by Juuldamen

2019-06-06 11:15 UTC, ronaldvandenbroek requested changes

2019-06-06 11:15 UTC, ronaldvandenbroek commented on Jenkinsfile
> +    sonar_exclusions: 'src/main.ts,**/concretes/peer.ts,**/socketIO/**/*,**/__tests__/**/*,**/mocks/**/*',
peer.ts should not be included just to artificially boost coverage levels

2019-06-11 07:35 UTC, hugovandevliert approved these changes

2019-06-11 07:35 UTC, ronaldvandenbroek approved these changes

2019-06-11 07:36 UTC, merged